spring:
  application:
    name: aeronaveV2

  datasource:
    url: jdbc:postgresql://dpg-d765em14tr6s73dffgp0-a:5432/usermanagement_xyll
    username: user
    password: vSwuRiiCt7Ce29wFohzZ4ABwN2JGsyxA
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  cors:
    allowed-origins: "https://69d46761ae4b7f00d734502c--sdteste.netlify.app/"

server:
  port: ${PORT:8080}
  address: 0.0.0.0